# Generated by Django 2.0.5 on 2018-05-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("staff", "0002_project")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        )
    ]
